config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :order_details, only: [:update]
    resources :orders, only: [:show, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, except: [:destroy]
  end
  get 'admin' => 'admin/homes#top', as:'top'

  scope module: :public do
    resources :addresses, except: [:new, :show]

    get 'orders/complete'
    resources :orders, only: [:new, :create, :index, :show]
    post 'orders/confirm'

    delete 'cart_items/destroy_all'
    resources :cart_items, only: [:index, :update, :destroy, :create]

    get 'customers/my_page' => 'customers#show'
    get 'customers/information/edit' => 'customers#edit'
    patch 'customers/information' => 'customers#update'
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    patch 'customers/withdraw' => 'customers#withdraw'

    resources :items, only: [:index, :show]

    root to: 'homes#top'
    get 'about' => 'homes#about', as:'about'
  end

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @customers=Customer.page(params[:page])
  end

  def show
    @customer=Customer.find(params[:id])
  end

  def edit
    @customer=Customer.find(params[:id])
  end

  def update
    @customer=Customer.find(params[:id])
    @customer.update(customer_params)
    flash[:notice] = "顧客情報の更新が完了しました"
    redirect_to admin_customers_path
  end
  private
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postal_code, :address, :telephone_number, :is_deleted)
  end
end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 mx-auto">
      <h4 class="m-3"><span class="bg-light"><%= @customer.last_name %><%= @customer.first_name %>さんの会員情報編集</span></h4>
      <%=form_with model: @customer, url:admin_customer_path(@customer.id), method: :patch do |f| %>
        <table cellpadding="5">
          <tr>
            <th><%= f.label :'会員ID' %></th>
            <td><%= @customer.id %></td>
          </tr>
          <tr>
            <th><%= f.label :'氏名' %></th>
            <td><%= f.text_field :last_name %></td>
            <td><%= f.text_field :first_name %></td>
          </tr>
          <tr>
            <th><%= f.label :'フリガナ' %></th>
            <td><%= f.text_field :last_name_kana %></td>
            <td><%= f.text_field :first_name_kana %></td>
          </tr>
          <tr>
            <th><%= f.label :'郵便番号' %></th>
            <td><%= f.text_field :postal_code %></td>
          </tr>
          <tr>
            <th><%= f.label :'住所' %></th>
            <td colspan="2"><%= f.text_field :address, class:"w-100" %></td>
          </tr>
          <tr>
            <th><%= f.label :'電話番号' %></th>
            <td><%= f.telephone_field :telephone_number %></td>
          </tr>
          <tr>
            <th><%= f.label :'メールアドレス' %></th>
            <td><%= f.email_field :email %></td>
          </tr>
          <tr>
            <th><%= f.label :'会員ステータス' %></th>
            <td>
              <%= f.radio_button :is_deleted, false %>
              <%= f.label :is_deleted, "有効", value: false, style: "display: inline-block;" %>
              <%= f.radio_button :is_deleted, true %>
              <%= f.label :is_deleted, "退会", value: true, style: "display: inline-block;" %>
            </td>
          </tr>
          <tr>
            <th></th>
            <td><%= f.submit "変更を保存", class:"btn btn-success px-4" %></td>
          </tr>
        </table>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 mx-auto">
      <div class="border-bottom border-dark">
        <h4 class="m-3"><span class="bg-light">会員一覧</span></h4>
      </div>
      <% @customers.each do |customer| %>
        <table style="width:100%">
          <tr class="table-secondary">
            <th style="width:10%">会員ID</th>
            <th style="width:30%">氏名</th>
            <th style="width:30%">メールアドレス</th>
            <th style="width:30%">ステータス</th>
          </tr>
          <tr>
            <td><%= customer.id %></td>
            <td>
              <%= link_to admin_customer_path(customer.id) do %>
                <%= customer.last_name %><%= customer.first_name %>
              <% end %>
            </td>
            <td><%= customer.email %></td>
            <td>
              <% if customer.is_deleted %>
                <span class="text-secondary font-weight-bold">退会</span>
              <% elsif %>
                <span class="text-success font-weight-bold">有効</span>
              <% end %>
            </td>
          </tr>
        </table>
      <% end %>
      <%= paginate @customers %>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 mx-auto">
      <h4 class="m-3"><span class="bg-light"><%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細</span></h4>
      <table cellpadding="5">
        <tr>
          <th>会員ID</th>
          <td><%= @customer.id %></td>
        </tr>
        <tr>
          <th>氏名</th>
          <td><%= @customer.last_name %> <%= @customer.first_name %></td>
        </tr>
        <tr>
          <th>フリガナ</th>
          <td><%= @customer.last_name_kana %> <%= @customer.first_name_kana %></td>
        </tr>
        <tr>
          <th>郵便番号</th>
          <td><%= @customer.postal_code %></td>
        </tr>
        <tr>
          <th>住所</th>
          <td><%= @customer.address %></td>
        </tr>
        <tr>
          <th>電話番号</th>
          <td><%= @customer.telephone_number %></td>
        </tr>
        <tr>
          <th>メールアドレス</th>
          <td><%= @customer.email %></td>
        </tr>
        <tr>
          <th>会員ステータス</th>
          <td>
            <% if @customer.is_deleted %>
              <span class="text-secondary font-weight-bold">退会</span>
            <% elsif %>
              <span class="text-success font-weight-bold">有効</span>
            <% end %>
          </td>
        </tr>
      </table>
      <%= link_to '編集する', edit_admin_customer_path(@customer.id), class:"btn btn-success px-4 mt-3 ml-5" %>
      <%= link_to '注文履歴一覧を見る', top_path(customer_id: @customer.id), class:"btn btn-primary px-4 mt-3 ml-5" %>
    </div>
  </div>
</div>