config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :order_details, only: [:update]
    resources :orders, only: [:show, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, except: [:destroy]
  end
  get 'admin' => 'admin/homes#top', as:'top'

  scope module: :public do
    resources :addresses, except: [:new, :show]

    get 'orders/complete'
    resources :orders, only: [:new, :create, :index, :show]
    post 'orders/confirm'

    delete 'cart_items/destroy_all'
    resources :cart_items, only: [:index, :update, :destroy, :create]

    get 'customers/my_page' => 'customers#show'
    get 'customers/information/edit' => 'customers#edit'
    patch 'customers/information' => 'customers#update'
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    patch 'customers/withdraw' => 'customers#withdraw'

    resources :items, only: [:index, :show]

    root to: 'homes#top'
    get 'about' => 'homes#about', as:'about'
  end

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  
  def subtotal
    item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  belongs_to :genre
  has_one_attached :image

  def self.ransackable_attributes(auth_object = nil)
    ["introduction", "name"]
  end
  def self.ransackable_associations(auth_object = nil)
    []
  end
  
  def with_tax_price
    (price * 1.1).floor
  end
  def subtotal
    item.with_tax_price * amount
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details, dependent: :destroy
  belongs_to :customer
  enum payment_method: { credit_card:0, transfer:1 }
  enum order_status: { waiting_for_payment:0, confirmed_the_payment:1, under_construction:2, ready_for_shipping:3, shipped:4 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  enum making_status: { impossible_manufacture: 0, waiting_manufacture: 1, manufacturing: 2, finish: 3 }
  
  def subtotal
    item.with_tax_price * amount
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!
  def index
    @genres=Genre.all
    @genre=Genre.new
  end

  def create
    @genre=Genre.new(genre_params)
    @genre.save
    flash[:notice] = "ジャンルの新規作成が完了しました"
    redirect_to admin_genres_path
  end

  def edit
    @genre=Genre.find(params[:id])
  end

  def update
    @genre=Genre.find(params[:id])
    @genre.update(genre_params)
    flash[:notice] = "ジャンルの更新が完了しました"
    redirect_to admin_genres_path
  end

  private
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  def top
    @sum = 0
    if params[:customer_id].present?
      @customer=Customer.find(params[:customer_id])
      @orders=Order.where(customer_id: params[:customer_id]).page(params[:page])
    else
      @orders=Order.all.page(params[:page])
    end
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  def index
    @items=Item.page(params[:page])
  end

  def new
    @item=Item.new
    @genres=Genre.all
  end

  def create
    @item=Item.new(item_params)
    @item.save
    flash[:notice] = "商品の新規作成が完了しました"
    redirect_to admin_item_path(@item.id)
  end

  def show
    @item=Item.find(params[:id])
  end

  def edit
    @item=Item.find(params[:id])
    @genres=Genre.all
  end

  def update
    @item=Item.find(params[:id])
    @item.update(item_params)
    flash[:notice] = "商品情報の更新が完了しました"
    redirect_to admin_items_path
  end
  private
  def item_params
    params.require(:item).permit(:image, :name, :introduction, :price, :is_active, :genre_id)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!
  def show
    @sum = 0
    @order=Order.find(params[:id])
    @order_details=@order.order_details.all
  end

  def index
    @orders=Order.page(params[:page])
  end

  def update
    @order=Order.find(params[:id])
    @order_details = OrderDetail.where(order_id: @order.id)
    if @order.update(order_params)
      @order_details.update_all(making_status: 1) if @order.order_status == "confirmed_the_payment"
    end
    flash[:notice] = "注文情報の更新が完了しました"
    redirect_to admin_order_path(params[:id])
  end
  private
  def order_params
    params.require(:order).permit(:order_status)
  end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_q_for_item

  def set_q_for_item
  @q = Item.ransack(params[:q])
  end

 def after_sign_in_path_for(resource)
    case resource
    when Admin
      top_path
    when Customer
      customers_my_page_path
    end
 end

 def after_sign_out_path_for(resource)
    case resource
    when :admin   # ログアウト時はシンボルが返ってくる
      new_admin_session_path
    when :customer  # ログアウト時はシンボルが返ってくる
      root_path
    end
 end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 mx-auto">
      <h4 class="m-3"><span class="bg-light">ジャンル編集</span></h4>

      <div class="mb-4">
        <%= form_with model: @genre, url:admin_genre_path(@genre.id), method: :patch do |f| %>
          <%= f.label :'ジャンル名' %>
          <%= f.text_field :name, autofocus: true, class:"mx-5" %>
          <%= f.submit "変更を保存", class:"btn btn-success px-4" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 mx-auto">
      <h4 class="m-3"><span class="bg-light">ジャンル一覧・追加</span></h4>

      <div class="mb-4">
        <%= form_with model: @genre, url: admin_genres_path do |f| %>
          <%= f.label :'ジャンル名' %>
          <%= f.text_field :name, autofocus: true, placeholder: "ジャンル名", class:"mx-5" %>
          <%= f.submit "新規登録", class:"btn btn-success px-4" %>
        <% end %>
      </div>

      <table cellpadding="5" class="w-50">
        <tr class="border-top border-bottom">
          <th>ジャンル</th>
          <th></th>
        </tr>
        <% @genres.each do |genre| %>
          <tr class="border-bottom">
            <td><%= genre.name %></td>
            <td><%= link_to '編集する', edit_admin_genre_path(genre.id) , class:"btn btn-success px-4 mt-3" %></td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/admin/items/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 mx-auto">
      <h4 class="m-3"><span class="bg-light">商品編集</span></h4>

      <div class="mb-4">
        <%= form_with model: @item, url:admin_item_path(@item.id), method: :patch do |f| %>
          <table cellpadding="5" class="w-75 mx-auto">
            <tr>
              <td>商品画像</td>
              <td><%= f.file_field :image, accept:"image/*" %></td>
            </tr>
            <tr>
              <td><%= f.label :'商品名' %></td>
              <td><%= f.text_field :name, size: 40 %></td>
            </tr>
            <tr>
              <td><%= f.label :'商品説明' %></td>
              <td><%= f.text_area :introduction, size: "40x5" %></td>
            </tr>
            <tr>
              <td><%= f.label :'ジャンル' %></td>
              <td><%= f.collection_select :genre_id, @genres, :id, :name %></td>
            </tr>
            <tr>
              <td><%= f.label :'税抜価格' %></td>
              <td><%= f.number_field :price %>円</td>
            </tr>
            <tr>
              <td><%= f.label :'販売ステータス' %></td>
              <td>
                <%= f.radio_button :is_active, :true %>
                <%= f.label :is_active, "販売中", value: :true, style: "display: inline-block;" %>
                <%= f.radio_button :is_active, :false %>
                <%= f.label :is_active, "販売停止中", value: :false, style: "display: inline-block;" %>
              </td>
            </tr>
          </table>
          <div class="text-center">
            <%= f.submit "変更を保存", class:"btn btn-success px-4" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 mx-auto">
      <h4 class="m-3"><span class="bg-light">商品一覧</span></h4>
      <%= link_to new_admin_item_path do %>
        <i class="fas fa-plus-circle fa-pull-right fa-2x" style="color: gray;"></i>
      <% end %>
        <table cellpadding="5" style="width:100%" class="border-top border-dark">
          <tr class="table-secondary">
            <th style="width:10%">商品ID</th>
            <th style="width:30%">商品名</th>
            <th style="width:10%">税抜価格</th>
            <th style="width:30%">ジャンル</th>
            <th style="width:20%">ステータス</th>
          </tr>
          <% @items.each do |item| %>
            <tr>
              <td><%= item.id %></td>
              <td><%= link_to item.name, admin_item_path(item.id) %></td>
              <td><%= item.price.to_s(:delimited) %></td>
              <td><%= item.genre.name %></td>
              <td>
                <% if item.is_active %>
                  <span class="text-success font-weight-bold">販売中</span>
                <% elsif %>
                  <span class="text-secondary font-weight-bold">販売停止中</span>
                <% end %>
              </td>
            </tr>
          <% end %>
        </table>
      <%= paginate @items %>
    </div>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 mx-auto">
      <h4 class="m-3"><span class="bg-light">商品新規登録</span></h4>
      
      <%= form_with model: @item, url: admin_items_path do |f| %>
        <table cellpadding="5" class="w-75 mx-auto">
          <tr>
            <td>商品画像</td>
            <td><%= f.file_field :image, accept:"image/*" %></td>
          </tr>
          <tr>
            <td><%= f.label :'商品名' %></td>
            <td><%= f.text_field :name, placeholder: "商品名", class:"w-50" %></td>
          </tr>
          <tr>
            <td><%= f.label :'商品説明' %></td>
            <td><%= f.text_area :introduction, placeholder: "ここに説明文を記述します", class:"w-50" %></td>
          </tr>
          <tr>
            <td><%= f.label :'ジャンル' %></td>
            <td><%= f.collection_select :genre_id, @genres, :id, :name, include_blank: '--選択してください--', class:"w-50" %></td>
          </tr>
          <tr>
            <td><%= f.label :'税抜価格' %></td>
            <td><%= f.number_field :price, placeholder: "1000", class:"w-50" %>円</td>
          </tr>
          <tr>
            <td><%= f.label :'販売ステータス' %></td>
            <td>
              <%= f.radio_button :is_active, :true %>
              <%= f.label :is_active, "販売中", value: :true, style: "display: inline-block;" %>
              <%= f.radio_button :is_active, :false %>
              <%= f.label :is_active, "販売停止中", value: :false, style: "display: inline-block;" %>
            </td>
          </tr>
        </table>
        <div class="text-center">
          <%= f.submit "新規登録", class:"btn btn-success px-4 mt-3" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/show.html.erb
<h4 class="m-3"><span class="bg-light">商品詳細</span></h4>
<div class="container">
  <div class="row">
    <div class="col-4">
      <%= image_tag @item.image, class:"img-fluid" %>
    </div>
    <div class="col-7 offset-md-1">
      <table cellpadding="5">
        <tr>
          <th>商品名</th>
          <td><%= @item.name %></td>
        </tr>
        <tr>
          <th>商品説明</th>
          <td><%= @item.introduction %></td>
        </tr>
        <tr>
          <th>ジャンル</th>
          <td><%= @item.genre.name %></td>
        </tr>
        <tr>
          <th>税込価格<br>(税抜価格)</th>
          <td><%= @item.price.to_s(:delimited) %>（<%= number_with_precision(@item.price*1.1, delimiter: ",", precision: 3,strip_insignificant_zeros: true) %>）円</td>
        </tr>
        <tr>
          <th>販売ステータス</th>
          <td>
            <% if @item.is_active %>
              <span class="text-success font-weight-bold">販売中</span>
            <% elsif %>
              <span class="text-secondary font-weight-bold">販売停止中</span>
            <% end %>
          </td>
        </tr>
      </table>
      <div class="text-center">
        <%= link_to '編集する', edit_admin_item_path(@item.id), class:"btn btn-success px-4 mt-3" %>
      </div>
    </div>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 mx-auto">
      <h4 class="m-3"><span class="bg-light">注文履歴詳細</span></h4>
      <table cellpadding="5" style="width:100%">
        <tr>
          <th>購入者</th>
          <td>
            <%= link_to admin_customer_path(@order.customer.id) do %>
              <%= @order.customer.last_name %><%= @order.customer.first_name %></td>
            <% end %>
        </tr>
        <tr>
          <th>注文日</th>
          <td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
        </tr>
        <tr>
          <th>配送先</th>
          <td>〒<%= @order.shipping_postal_code %> <%= @order.shipping_address %><br><%= @order.shipping_name %></td>
        </tr>
        <tr>
          <th>支払方法</th>
          <td><%= @order.payment_method_i18n %></td>
        </tr>
        <tr>
          <th>注文ステータス</th>
          <td>
            <%=form_with model: @order, url:admin_order_path(@order.id), method: :patch do |f| %>
              <%= f.select :order_status, Order.order_statuses_i18n.invert, {} %>
              <%= f.submit '更新', class:"btn btn-success ml-3" %>
            <% end %>
          </td>
        </tr>
      </table>
    </div>
    <div class="col-9 border-top border-bottom mt-4">
      <table cellpadding="5" style="width:100%;">
        <tr>
          <th>商品名</th>
          <th>単価（税込）</th>
          <th>数量</th>
          <th>小計</th>
          <th>製作ステータス</th>
        </tr>
        <% @order_details.each do |order_detail| %>
          <tr>
              <td><%= order_detail.item.name %></td>
              <td><%= order_detail.item.with_tax_price.to_s(:delimited) %></td>
              <td><%= order_detail.amount %></td>
              <td><%= order_detail.subtotal.to_s(:delimited) %></td>
              <td>
                <%= form_with model: order_detail, url:admin_order_detail_path(order_detail.id), method: :patch do |f| %>
                  <%= f.select :making_status, OrderDetail.making_statuses_i18n.invert, {} %>
                  <%= f.submit '更新', class:"btn btn-success ml-2" %>
                <% end %>
              </td>
          </tr>
        <% end %>
      </table>
    </div>
    <div class="col-3 mt-4">
      <table>
        <tr>
          <th>商品合計</th>
          <td align="right">
              <% @order_details.each do |order_detail| %>
                <% @sum += order_detail.subtotal %>
              <% end %>
            <%= @sum.to_s(:delimited) %>円
          </td>
        </tr>
        <tr>
          <th>送料</th>
          <td align="right"><%= @order.postage.to_s(:delimited) %>円</td>
        </tr>
        <tr>
          <th>請求合計金額</th>
          <td align="right"><%= @order.total_amount.to_s(:delimited) %>円</td>
        </tr>
      </table>
    </div>
  </div>
</div>