config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :order_details, only: [:update]
    resources :orders, only: [:show, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, except: [:destroy]
  end
  get 'admin' => 'admin/homes#top', as:'top'

  scope module: :public do
    resources :addresses, except: [:new, :show]

    get 'orders/complete'
    resources :orders, only: [:new, :create, :index, :show]
    post 'orders/confirm'

    delete 'cart_items/destroy_all'
    resources :cart_items, only: [:index, :update, :destroy, :create]

    get 'customers/my_page' => 'customers#show'
    get 'customers/information/edit' => 'customers#edit'
    patch 'customers/information' => 'customers#update'
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    patch 'customers/withdraw' => 'customers#withdraw'

    resources :items, only: [:index, :show]

    root to: 'homes#top'
    get 'about' => 'homes#about', as:'about'
  end

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  
  def subtotal
    item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  belongs_to :genre
  has_one_attached :image

  def self.ransackable_attributes(auth_object = nil)
    ["introduction", "name"]
  end
  def self.ransackable_associations(auth_object = nil)
    []
  end
  
  def with_tax_price
    (price * 1.1).floor
  end
  def subtotal
    item.with_tax_price * amount
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details, dependent: :destroy
  belongs_to :customer
  enum payment_method: { credit_card:0, transfer:1 }
  enum order_status: { waiting_for_payment:0, confirmed_the_payment:1, under_construction:2, ready_for_shipping:3, shipped:4 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  enum making_status: { impossible_manufacture: 0, waiting_manufacture: 1, manufacturing: 2, finish: 3 }
  
  def subtotal
    item.with_tax_price * amount
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!
  def index
    @genres=Genre.all
    @genre=Genre.new
  end

  def create
    @genre=Genre.new(genre_params)
    @genre.save
    flash[:notice] = "ジャンルの新規作成が完了しました"
    redirect_to admin_genres_path
  end

  def edit
    @genre=Genre.find(params[:id])
  end

  def update
    @genre=Genre.find(params[:id])
    @genre.update(genre_params)
    flash[:notice] = "ジャンルの更新が完了しました"
    redirect_to admin_genres_path
  end

  private
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  def top
    @sum = 0
    if params[:customer_id].present?
      @customer=Customer.find(params[:customer_id])
      @orders=Order.where(customer_id: params[:customer_id]).page(params[:page])
    else
      @orders=Order.all.page(params[:page])
    end
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  def index
    @items=Item.page(params[:page])
  end

  def new
    @item=Item.new
    @genres=Genre.all
  end

  def create
    @item=Item.new(item_params)
    @item.save
    flash[:notice] = "商品の新規作成が完了しました"
    redirect_to admin_item_path(@item.id)
  end

  def show
    @item=Item.find(params[:id])
  end

  def edit
    @item=Item.find(params[:id])
    @genres=Genre.all
  end

  def update
    @item=Item.find(params[:id])
    @item.update(item_params)
    flash[:notice] = "商品情報の更新が完了しました"
    redirect_to admin_items_path
  end
  private
  def item_params
    params.require(:item).permit(:image, :name, :introduction, :price, :is_active, :genre_id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_q_for_item

  def set_q_for_item
  @q = Item.ransack(params[:q])
  end

 def after_sign_in_path_for(resource)
    case resource
    when Admin
      top_path
    when Customer
      customers_my_page_path
    end
 end

 def after_sign_out_path_for(resource)
    case resource
    when :admin   # ログアウト時はシンボルが返ってくる
      new_admin_session_path
    when :customer  # ログアウト時はシンボルが返ってくる
      root_path
    end
 end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="mt-3">
      <div class="container">
        <div class="row">
          <div class="col-3">
            <h2 class="border border-dark px-4 d-inline-block">LOGO</h2>
          </div>
          <div class="col-9">
            <% if admin_signed_in? %>
              <div style="text-align: right;">
                <%= link_to "商品一覧", admin_items_path, class:"btn btn-light px-4" %>
                <%= link_to "会員一覧", admin_customers_path, class:"btn btn-light px-4" %>
                <%= link_to "注文履歴一覧", top_path, class:"btn btn-light px-4" %>
                <%= link_to "ジャンル一覧", admin_genres_path, class:"btn btn-light px-4" %>
                <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class:"btn btn-light px-4" %>
              </div>
            <% elsif customer_signed_in? %>
              <div style="text-align: right;">
                <%= link_to "マイページ", customers_my_page_path, class:"btn btn-light px-4" %>
                <%= link_to "商品一覧", items_path, class:"btn btn-light px-4" %>
                <%= link_to "カート", cart_items_path, class:"btn btn-light px-4" %>
                <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class:"btn btn-light px-4" %>
              </div>
              ようこそ、<%= current_customer.last_name %>さん！
            <% else %>
              <div style="text-align: right;">
                <%= link_to "About", about_path, class:"btn btn-light px-4" %>
                <%= link_to "商品一覧", items_path, class:"btn btn-light px-4" %>
                <%= link_to "新規登録", new_customer_registration_path, class:"btn btn-light px-4" %>
                <%= link_to "ログイン", new_customer_session_path, class:"btn btn-light px-4" %>
              </div>
            <% end %>
            <%= search_form_for @q, url: admin_items_path do |f| %>
              <table align="right" style="width:30%;">
                <tr>
                  <td><%= f.search_field :name_or_introduction_cont, class: 'form-control', placeholder: 'Search' %></td>
                  <td>
                    <%= f.button :type => "submit" do %>
                      <i class='fas fa-search'></i>
                    <% end %>
                  </td>
                </tr>
              </table>
            <% end %>
          </div>
        </div>
      </div>

    </header>
    <main>
      <%= flash[:notice] %>
      <%= flash[:alert] %>
      <%= yield %>
    </main>
    <footer>

    </footer>
  </body>
</html>